### ISSUE TITLE
down

### ISSUE THREAD

**Issue by SuperOP535** [vladdeSV/mee6calc.xyz#2]
offline

**Comment by vladdeSV** [comment]
yeah i know, i dont own the domain anymore

**Comment by SilBoydens** [comment]
there is a copy of this running on the documentation of Mee6: http://mee6.github.io/Mee6-documentation/mee6calc/

**Comment by vladdeSV** [comment]
wait whaa? that's cool i guess.

not maintaining this anymore though.

**Comment by SilBoydens** [comment]
i think i put it on the Mee6 docs the day you made this repository, i did inform you back then.

if there needs to be a change on this then i will hapely provide a pull request, don't worry

**Comment by SuperOP535** [comment]
Ok
